name: fyp2
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  icons_plus: ^5.0.0
  animated_splash_screen: ^1.3.0
  shared_preferences: ^2.2.2
  get: ^4.6.6
  fluttertoast: ^8.2.2
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0
  http: ^1.1.2
  cached_network_image: ^3.1.0
  flutter_typeahead: ^5.0.2
  dropdown_search: ^5.0.6
  youtube_player_flutter: ^8.1.2
  flutter_rating_bar: ^4.0.1
  provider: ^6.1.2
  email_validator: ^2.1.17
  flutter_spinkit: ^5.1.0
  intl: ^0.19.0
  shimmer: ^3.0.0
  sqflite: ^2.3.2
  flutter_background_service: ^5.0.5
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  assets:
    - assets/chef.png
    - assets/bike.png
    - assets/home.png
    - assets/login.png
    - assets/signup.png
    - assets/image01.png
    - assets/image02.png
    - assets/image03.png
    - assets/image04.png
    - assets/image05.png
    - assets/images06.png
    - assets/recipes.png
    - assets/delivery.png
    - assets/food-recipe.png
    - assets/grocery-image.png
    - assets/logo.png
  uses-material-design: true

  fonts:
    - family: PlaypenSans
      fonts:
        - asset: font/PlaypenSans-Regular.ttf
    - family: Anton
      fonts:
        - asset: font/Anton-Regular.ttf
